### ISSUE TITLE
Compilado en Windows

### ISSUE THREAD

**Issue by vfontana0** [tiflo-sf/simae#19]
La funcion 'moverASimaeGrammars' es incompatible con Windows.

![image](https://user-images.githubusercontent.com/70077312/156193636-a7d5e1b7-ccfb-462f-be0b-bb9414f857b0.png)

**Comment by Patacon13** [comment]
Se puede, según el S.O. que corre el programador ejecutar distinto código.
https://stackoverflow.com/questions/8796615/modify-gradles-runtime-dependencies-according-to-operation-system

El problema en la función moverASimaeGrammars (disponible en la PR #17, no en el código del proyecto) podría solucionarse usando un switch según el lenguaje que corra, quedando algo del estilo:

```Groovy
switch(System.getProperty('os.name').toLowerCase().split()[0]) {
  case 'linux':
    workingDir './build/generated-src/antlr/main/'
    executable "sh"
    args "-c", "mkdir -p simae/grammars/; mv *.* simae/grammars"
    break
  case 'windows':
    //Codigo de windows
    break
  default:
    throw new Exception('Unknown OS')
}
```

**Comment by Patacon13** [comment]
> Se puede, según el S.O. que corre el programador ejecutar distinto código. https://stackoverflow.com/questions/8796615/modify-gradles-runtime-dependencies-according-to-operation-system
> 
> El problema en la función moverASimaeGrammars (disponible en la PR #17, no en el código del proyecto) podría solucionarse usando un switch según el lenguaje que corra, quedando algo del estilo:
> 
> ```groovy
> switch(System.getProperty('os.name').toLowerCase().split()[0]) {
>   case 'linux':
>     workingDir './build/generated-src/antlr/main/'
>     executable "sh"
>     args "-c", "mkdir -p simae/grammars/; mv *.* simae/grammars"
>     break
>   case 'windows':
>     //Codigo de windows
>     break
>   default:
>     throw new Exception('Unknown OS')
> }
> ```

Agregando a esto, puede que también convenga también intentar tener una alternativa para mac
