### ISSUE TITLE
Problema de codificación en Licencia e Instrucciones en instalador

### ISSUE THREAD

**Issue by Patacon13** [tiflo-sf/simae#44]
Al crear el instalador hay problemas en la licencia y en las instrucciones de instalación los acentos no funcionan por problemas en la codificación que acepta Github para archivos de texto.
![image](https://user-images.githubusercontent.com/42981462/200934729-9253fa5c-b096-47a7-b2af-3782b127117a.png)

**Comment by CesarBallardini** [comment]
agregamos el BOM a LICENSE

* en hexadecimal el BOM UTF-8 es 0xEF,0xBB,0xBF
* en octal es 357, 273, 277



```bash
echo -en "\0357\0273\0277" |  cat - LICENSE > pp
mv pp LICENSE 
git add LICENSE
```

# Referencias

* https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8
